- name: A simple playbook that prints to the screen
  hosts: all   # this is typical aap playbook design
  gather_facts: false   # not using
  connection: ansible.builtin.local  # debug, sdk (http operations)

  vars_files:
  - vars/playbook09_debug_vars.yml

  tasks:
  - name: Print to the screen
    ansible.builtin.debug:
       msg: "intro to aap"

  - name: Print var from our var file
    ansible.builtin.debug:
       var: acmebank_var
